/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BirdnestNt {
    }
}
declare global {
    interface HTMLBirdnestNtElement extends Components.BirdnestNt, HTMLStencilElement {
    }
    var HTMLBirdnestNtElement: {
        prototype: HTMLBirdnestNtElement;
        new (): HTMLBirdnestNtElement;
    };
    interface HTMLElementTagNameMap {
        "birdnest-nt": HTMLBirdnestNtElement;
    }
}
declare namespace LocalJSX {
    interface BirdnestNt {
    }
    interface IntrinsicElements {
        "birdnest-nt": BirdnestNt;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "birdnest-nt": LocalJSX.BirdnestNt & JSXBase.HTMLAttributes<HTMLBirdnestNtElement>;
        }
    }
}
